# panfrost is still a bit unstable on the mali t720, so lets better disable it
# by default - to enable it, simply comment out the last three lines
#
# to be on the safe side, better run an update-initramfs -c -k kernel-version
# after potentially uncommenting the following lines to disable panfrost
blacklist drm_shmem_helper
blacklist gpu_sched
blacklist panfrost
